### ISSUE TITLE
Upload message on Desktop add-in

### ISSUE THREAD

**Issue by jdduh** [PSU-CSAR/django-ebagis#67] opened 2017-08-27 22:39 UTC
I'm not sure if this is the desktop add-in issue or the sever API issue. The addin GUI shows that there is an error during the upload, but ebagis seems to be OK with the upload.

![image](https://user-images.githubusercontent.com/11510708/29754602-82df9cb8-8b3d-11e7-8295-10192cd31772.png)

![image](https://user-images.githubusercontent.com/11510708/29754617-beb0ee7c-8b3d-11e7-814a-d6ad94eeb43f.png)

**Comment by lbross** [comment] 2017-08-28 18:09
I just uploaded two AOI's, including yampa_aoi, without any errors. Hopefully @jkeifer can check the logs and see what happened yesterday. If memory serves, and it doesn't always, I think I have tried uploading yampa_aoi previously and it failed with the timeout error on larger aoi's that we've been unable to resolve. So it is good I was able to upload today.

@jdduh: Can you try again by either deleting the first one or changing the name? If it fails, maybe try logging on as testuser and see if it's a user account issue?

**Comment by jdduh** [comment] 2017-08-29 01:03
The sever doesn't have any log indicating an error.
I re-uploaded the same AOI, the add-in's error message appears even when the server still processing the request. This could be a time-out error on the desktop add-in.

![image](https://user-images.githubusercontent.com/11510708/29799820-2f64e5b4-8c1b-11e7-8d97-201146b9b216.png)

**Comment by jkeifer** [comment] 2017-08-29 01:05
Watching the server logs during the second attempt I saw this line:

`2017-08-29 00:58:29 131.252.97.90 POST /api/rest/aois/ - 443 - 208.71.200.90 HTTP/1.1 - - - test.ebagis.geog.pdx.edu 200 0 0 1284 67221644 42598 multipart/form-data;+boundary=---------------------------8d4ee3e499b7e33`

The `200` after the `test.ebagis.geog.pdx.edu` indicates that the server responded with a 200 response, which indicates the request was successful.

**Comment by lbross** [comment] 2017-08-29 17:48
Since I'm not getting the error uploading yampa_aoi as testUser, this leads me to believe that this is an issue either with the jduh user account or with a different version of ArcGIS. I don't think it's a timeout because that shows up as a 500 from the server. Not sure what you want to try next. I could do a debug version of the add-in that saves the details of the error message?

**Comment by lbross** [comment] 2017-08-29 18:14
It may be a timeout as I just got an error on yampa_aoi. I set the timeout to infinity on the client side and am still waiting. What is the url for the upload requests status page that Geoffrey shows above? Never mind, I found it. My upload still isn't showing as processing so it is different behavior than @jdduh.

**Comment by jdduh** [comment] 2017-08-29 18:24
The URL is account-specific. You might not be able to access the exact page.
https://test.ebagis.geog.pdx.edu/accounts/uploads/

You can find the upload queue page by clicking on the account menu.
![image](https://user-images.githubusercontent.com/11510708/29837246-799edc0c-8cac-11e7-82db-61aca46faac2.png)

**Comment by lbross** [comment] 2017-08-29 18:31
I will work on a debug version that writes the stacktrace to a log. I am seeing different behavior than @jdduh so not sure what to do otherwise. If I don't set the timeout for the webrequest, I get this exception:
System.Net.WebException: The operation has timed out
   at System.Net.HttpWebRequest.GetResponse()
   at BAGIS_ClassLibrary.WebservicesModule.BA_UploadMultiPart(String webserviceUrl, String strToken, String fileName, String filePath, String comment)
And the upload never reaches the server as far as I can see. This is not a new issue.

If I set the timeout to infinite, ArcMap hangs and the upload never reaches the server that I can see. Not sure if the server is timing out. This is the first time I have tried setting the timeout.

Note that I am near the requested maximum for my hours so if you want to wait until October to track this down, we can.

**Comment by jkeifer** [comment] 2017-08-29 18:47
What is your default timeout setting? When you set it to infinity you still got a timeout error; how long did that take?

@lbross Out of curiosity, what is the upload speed of your internet connection? Do you have your PSU VPN running when testing?

I changed the request timeout on the server to 300 seconds; can you try again? I do not see any upload requests since Geoffrey's last night. If you are trying to upload this morning, then it appears likely that if IIS times out waiting for the client to upload (previously 120 seconds) no request is even logged.

I don't know how a timeout on the server side could possibly create this problem, however, as the logs above show that Geoffrey's upload of yampa was successfully received. That suggests to me that it could not have timed out anywhere.

Also, @lbross, you say the response from the server was 500: are you saying that because that is what condition would cause the desktop addin to show an upload error, or do you have something that actually shows a 500 error was received? I don't see any 500 errors in the webserver logs.

**Comment by lbross** [comment] 2017-08-29 19:06
According to the API, the default timeout setting is 100,000 milliseconds (100 seconds). When I set it to infinity, I never got a response/error. I finally gave up and killed ArcMap after waiting about 15 minutes. With the .net API upload, I have to wait until the httprequest has finished uploading before I can proceed.

My upload speed is approximately 5 mbps. No VPN connected.

I was able to upload yampa_aoi_2 successfully about 10 minutes ago. Nothing changed from my previous attempts. I think it was because I was trying to capture the error to write a log :-(.

However, I just renamed it, tried again, and it failed. yampa_aoi_3. What I fail to understand is why @jdduh  upload attempts are received and processed by the server while mine are not. It seems as if the issue may not be the same.

I am actually currently not getting any response from the server when I encounter this error. The Response property is null. The exception handling for the WebException object is not standard so I'm trying to figure out how to parse it and write a log so we can capture @jdduh error. This is all I have so far for my error:

System.Net.WebException: The operation has timed out
   at System.Net.HttpWebRequest.GetResponse()
   at BAGIS_ClassLibrary.WebservicesModule.BA_UploadMultiPart(String webserviceUrl, String strToken, String fileName, String filePath, String comment)}

**Comment by jdduh** [comment] 2017-08-29 19:18
I would like to identify the source of the issue for now and can wait until October to have the issue corrected. I'm using BAGIS-H Version 1.6.4 on ArcGIS 10.4.1. My upload speed at home is similar to what Lesley has. I also tried the upload at Beaverton City library. I didn't use VPN in either case.

**Comment by jkeifer** [comment] 2017-08-29 19:24
Assuming you can get a full 5 Mbps upload speed, you should expect to upload the yampa AOI (65 MB in size) in about 104 seconds (65 MB / (5 Mb/ 8 bit/byte) = 104). To actually get the full 5 Mbps throughput may be unlikely depending on other traffic, your ISP, and other inefficiencies/factors.

If your timeout is 100 seconds, it sounds like you're not going to complete the request before timing out on your side. As I said, I changed the timeout on the server side about 30 minutes ago to 300 seconds, but if you still have yours set to 100 seconds, then I don't know why you would have had any change in behavior, unless you we getting more than your 5 Mbps upload speed for a couple minutes while attempting yampa_aoi_2. It could be possible depending on your ISP and how they're rate limiting your speed.

To be frank, I rather than depending on long-running HTTP requests transmitting a bunch of data, the right solution here would be to use chunked uploads and more small requests. I know you tried to implement that previously and had issues, but I'm concerned that the non-chunked uploads will be inherently unreliable for the exact timing reasons it seems you're running into.

I do agree, the issues you're seeing into do not seem to be the same that @jdduh experienced.

**Comment by jdduh** [comment] 2017-08-29 20:12
@lbross, how about creating a new eBAGIS account and do the upload from the new account?

**Comment by lbross** [comment] 2017-08-29 20:12
[yampa_error.txt](https://github.com/PSU-CSAR/django-ebagis/files/1261602/yampa_error.txt)
More confused then ever. Changed my timeout to match the server and got the attached response from the server. My guess is that yampa_aoi_3 will continue to upload. Continuing to tweak error handling.
[yampa_error.txt](https://github.com/PSU-CSAR/django-ebagis/files/1261603/yampa_error.txt)

**Comment by jkeifer** [comment] 2017-08-29 22:17
@lbross  The error you got in the .txt file is what I'd expect to see if you hit a 500 error. I don't remember the exact reasoning, but I think it is because I added a custom 500 error page and with debugging on it doesn't work correctly. I'll need to see about fixing that so you'd get a real 500 error page with real debug info.

I did find the portion of the log that goes with the 500 error:

```
[29/Aug/2017 13:04:54] DEBUG [django.template:925] Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "C:\Anaconda_x86\envs\ebagis_beta\lib\site-packages\django\template\base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>'
[29/Aug/2017 13:04:54] DEBUG [django.template:925] Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "C:\Anaconda_x86\envs\ebagis_beta\lib\site-packages\django\template\base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (None:None) ^api/rest/>'
[29/Aug/2017 13:04:54] DEBUG [django.template:925] Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "C:\Anaconda_x86\envs\ebagis_beta\lib\site-packages\django\template\base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'allauth.urls' from 'C:\\Anaconda_x86\\envs\\ebagis_beta\\lib\\site-packages\\allauth\\urls.pyc'> (None:None) ^accounts/>"
[29/Aug/2017 13:04:54] WARNING [django.request:152] Not Found: /500.html
```

That traceback is a bit cryptic, but it leads me to this question: can you confirm what URLs you could be hitting during the upload process?

**Comment by lbross** [comment] 2017-08-29 22:18
Just realized users don't have the capability to logout of eBAGIS from ArcMap. Is this something we want to add? If so, do you want it before 8/31?

**Comment by lbross** [comment] 2017-08-29 23:02
Some updates from my work this afternoon:
1. I have tried several uploads of yampa_aoi_3 this afternoon. All failed with the timeout error. For the case right after lunch where I got the 500 error, it does not appear to have continued processing like it did for @jduh. The aoi is not on in the database.
2. I created a new user account, lbross, and used it from the desktop add-in to upload yampa_aoi_3. Still got the timeout error.
3. @jkeifer I am hitting https://test.ebagis.geog.pdx.edu/api/rest/aois/ with a post when I try to upload. This is the opening border of the multipart form if it is of any use: -----------------------------8d4eef233de9ec6  Content-Disposition: form-data; name="file"; filename="yampa_AOI_3.zip"  Content-Type: application/zip    . Starting to think the 500 was an anomaly though.
4. I compiled a new add-in with enhanced error logging capabilities for @jdduh  to try. Download from [here](https://github.com/PSU-CSAR/vb-bagis-h/releases/tag/1.6.5). It is version 1.6.5. In addition to the MessageBox, it also writes a text file called ebagis_upload_error.txt to the root of the AOI folder you are trying to upload.
5. I don't hold out much hope for getting the chunked upload to work. Conceptually it isn't that difficult but .NET support for the PUT method is nil. That is where I got stuck before. See issue #53. Maybe there is another way to write the endpoint? Probably better to wait until October for this though.

**Comment by jkeifer** [comment] 2017-08-29 23:12
re 1-3:The 500 is certainly odd. Thanks for confirming the endpoint you hit to get it. I don't quite know what to make of it at the moment. It is good to know that it hasn't reoccurred (though unfortunate that your can't reproduce it, as it is obviously a bug).

re 4: Hopefully @jdduh will be able to replicate and then we'll get some better info.

re 5: I don't know if you told me that was the reason chunking didn't work before, but I think it would be possible to rework the upload endpoint to take chunks with a POST. It offends my REST sensibilities, as multiple PUTs of the same chunk would be idempotent, and POST would suggest otherwise. But I won't complain too much if it is what we have to do to get chunking working on your end. I think doing so would fix any timeouts you're seeing.

**Comment by jdduh** [comment] 2017-08-30 00:56
I no longer get an error message when uploading an AOI with BAGIS-H 1.6.5. @lbross,  please document what was done and close the issue. Thanks for fixing the issue.

**Comment by lbross** [comment] 2017-08-30 22:00
Set timeout on request in BA_UploadMultiPart() to 300 seconds to match the server. Don't understand why this resolve the issue but glad @jdduh is no longer getting the error. Follow-up on [problems with large uploads](https://github.com/PSU-CSAR/django-ebagis/issues/53) in October.

**Closed as completed by lbross** 2017-08-30 22:00 UTC
Labels: bug

**Comment by jkeifer** [comment] 2017-08-30 22:12
This might be a crazy thought. We had the following timeouts before:

Server - 120s
Client - 100s

If the upload completed within 100s, but the server response took a few seconds and got the total time over 100s before it responded, then the client could have timed out while the server didn't. If this is correct, then I think it means that you always want your client to have the same or longer timeout than your server.

Of course, I don't know how dependent the server is on underlying network layers: does it keep the connection open and the request running until TCP has gotten its final ACK back from the client? Or does the server not care about that and will consider the request completed regardless of whether the client has confirmed receipt of the response? The above idea is dependent upon the latter.

Assuming my idea is correct, then the crazy part is that @jdduh was able to duplicate the problem. I don't see how it would be so consistent in time to trigger the issue repeatedly, particularly when he duplicated the problem at different locations using different underlying internet connections. The only thing I can think is that he had his VPN up, the upload was going through the VPN, and file transfers within the VPN are consistently rate limited by PSU to some speed lower than the upload rates on any connection over which he tested. In such a scenario I could see the upload taking relatively the same amount of time on multiple attempts.

**Comment by jdduh** [comment] 2017-08-30 23:11
I didn't have VPN up during all my uploads.
